[package]
name = "day3"
version = "0.1.0"
authors = ["Gordon Tyler <gordon.tyler@synaptivemedical.com>"]
edition = "2018"

[dependencies]
regex = "1.1.0"
lazy_static = "1.2.0"
shared = { path = "../shared" }
