[package]
name = "day10"
version = "0.1.0"
authors = ["Gordon Tyler <gordon@doxxx.net>"]
edition = "2018"

[dependencies]
regex = "1.1.0"
lazy_static = "1.2.0"
piston_window = "0.81.0"
img = { package = "image", version = "0.20.1" }
